// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Board struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt time.Time
}

type Reminder struct {
	ID        int32
	UserID    int32
	TaskID    int32
	Message   sql.NullString
	RemindAt  time.Time
	Frequency sql.NullInt64
	CreatedAt time.Time
}

type State struct {
	ID        int32
	UserID    int32
	Name      string
	BoardID   int32
	CreatedAt time.Time
}

type Task struct {
	ID        int32
	UserID    int32
	Title     string
	Content   string
	StateID   int32
	CreatedAt time.Time
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
