CREATE TABLE reminders (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    message TEXT NULL,
    remind_at TIMESTAMP NOT NULL,
    frequency INTERVAL NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
